<?php
/**
 * Catalogue des formes juridiques INSEE.
 */

declare(strict_types=1);

namespace GestiWork\Domain\Tiers;

final class LegalFormCatalog
{
    /**
     * Retourne le mapping code -> libellé.
     */
    public static function labels(): array
    {
        return [
            '0000' => 'Non déterminé',
            '1000' => 'Entrepreneur individuel',
            '1100' => 'Services déconcentrés de l’État',
            '1200' => 'Collectivités territoriales',
            '1300' => 'Établissements publics administratifs',
            '1400' => 'Organismes de sécurité sociale',
            '1500' => 'Autres personnes morales de droit public',
            '1900' => 'Administration publique',
            '2110' => 'Société civile immobilière',
            '2210' => 'Société civile professionnelle',
            '2220' => 'Société civile de moyens',
            '2230' => 'Société civile d’attribution',
            '2240' => 'Groupement foncier agricole',
            '2250' => 'Société civile agricole',
            '2290' => 'Autre société civile',
            '2385' => 'Société coopérative artisanale',
            '2395' => 'Société coopérative d’intérêt collectif',
            '2600' => 'Profession libérale',
            '2700' => 'Syndic de copropriété',
            '2800' => 'Autres groupements de droit privé',
            '3110' => 'SA à conseil d’administration',
            '3120' => 'SA à directoire',
            '3150' => 'Société en commandite par actions',
            '3205' => 'Société par actions simplifiée (SAS)',
            '3220' => 'Société par actions simplifiée unipersonnelle (SASU)',
            '3290' => 'Autres sociétés par actions',
            '3410' => 'SARL, société à responsabilité limitée',
            '3420' => 'SARL à associé unique ou EURL',
            '3490' => 'Autres SARL',
            '4110' => 'Entrepreneur individuel',
            '4120' => 'Micro-entrepreneur (EI)',
            '4130' => 'Exploitant agricole',
            '4140' => 'Profession libérale',
            '4150' => 'Artisan',
            '4160' => 'Commerçant',
            '4170' => 'Officier public ou ministériel',
            '4180' => 'Autre entrepreneur individuel',
            '5191' => 'Société en nom collectif',
            '5192' => 'Société en commandite simple',
            '5193' => 'Société en participation',
            '5194' => 'Société créée de fait',
            '5195' => 'Association en participation',
            '5196' => 'SARL coopérative',
            '5305' => 'Coopérative agricole',
            '5307' => 'Société d’intérêt collectif agricole (Sica)',
            '5310' => 'Union de coopératives agricoles',
            '5320' => 'Autres sociétés coopératives agricoles',
            '5370' => 'Société d’assurance mutuelle',
            '5385' => 'Société mutualiste',
            '5410' => 'Société coopérative artisanale',
            '5420' => 'Société coopérative d’intérêt collectif',
            '5430' => 'Coopérative maritime',
            '5440' => 'Coopérative de transport',
            '5450' => 'Société coopérative de construction',
            '5460' => 'Autres sociétés coopératives',
            '5499' => 'Société à responsabilité limitée (SARL)',
            '5505' => 'Société coopérative d’HLM',
            '5510' => 'Société d’économie mixte',
            '5520' => 'Société publique locale',
            '5550' => 'Société d’aménagement foncier et d’établissement rural',
            '5599' => 'Autres sociétés coopératives',
            '5605' => 'Société à mission',
            '5710' => 'Société par actions simplifiée (SAS)',
            '5720' => 'Société par actions simplifiée unipersonnelle (SASU)',
            '5785' => 'Société anonyme (SA)',
            '5800' => 'Autres formes de société commerciale',
            '6310' => 'Association déclarée',
            '6311' => 'Association déclarée d’utilité publique',
            '6312' => 'Association non déclarée',
            '6313' => 'Association de droit local',
            '6320' => 'Congrégation',
            '6330' => 'Fondation',
            '6340' => 'Syndicat de copropriétaires',
            '6400' => 'Autres personnes morales de droit privé',
            '6540' => 'Autres groupements de droit privé',
            '7112' => 'Organisme professionnel',
            '7120' => 'Organisation patronale',
            '7210' => 'Syndicat de salariés',
            '7220' => 'Syndicat mixte',
            '7312' => 'Association syndicale autorisée',
            '7313' => 'Association syndicale libre',
            '7314' => 'Association foncière urbaine',
            '7320' => 'Comité d’entreprise ou similaire',
            '7380' => 'Autres collectivités ou regroupements',
            '8110' => 'Établissement public industriel ou commercial',
            '8120' => 'Établissement public local',
            '8130' => 'Établissement public de santé',
            '8140' => 'Autres établissements publics',
            '8210' => 'Groupement d’intérêt public',
            '8310' => 'Autre organisme public à caractère industriel ou commercial',
            '9220' => 'Syndicat de salariés',
            '9999' => 'Autre catégorie juridique',
        ];
    }
}
